media:
  input: img
  output: img

collections:
  - id: main_pages
    label: "Главные страницы"
    type: files
    files:
      - id: index_en
        label: "Главная страница (EN)"
        path: index.html
        fields:
          - id: body
            label: "Исходный код страницы"
            type: text