media:
  input: img
  output: img

collections:
  - id: main_pages
    label: Главные страницы (Index)
    type: files
    files:
      - id: index_en
        label: Главная страница (EN)
        path: index.html
        fields:
          - id: company_title
            label: Главный заголовок (Hero)
            type: string
            html:
              selector: ".main-block__slide:nth-child(1) .swiper-slide__title"
          - id: company_subtitle
            label: Подзаголовок (Hero)
            type: string
            html:
              selector: ".main-block__slide:nth-child(1) .swiper-slide__sub-title"
          - id: who_we_are
            label: Блок "Who We Are" (Текст)
            type: rich-text
            html:
              selector: ".whoweare__text"

      - id: index_ua
        label: Головна сторінка (UA)
        path: index_ua.html
        fields:
          - id: company_title_ua
            label: Головний заголовок (Hero)
            type: string
            html:
              selector: ".main-block__slide:nth-child(1) .swiper-slide__title"
          - id: company_subtitle_ua
            label: Підзаголовок (Hero)
            type: string
            html:
              selector: ".main-block__slide:nth-child(1) .swiper-slide__sub-title"
          - id: who_we_are_ua
            label: Блок "Хто ми такі" (Текст)
            type: rich-text
            html:
              selector: ".whoweare__text"

  - id: products
    label: Страницы продуктов
    type: files
    files:
      - id: product_pallets
        label: Pallets
        path: product_pallets.html
        fields:
          - id: title_grade1
            label: Заголовок Grade 1
            type: string
            html:
              selector: ".product:nth-of-type(1) .header-product__title"
          - id: desc_grade1
            label: Описание Grade 1
            type: rich-text
            html:
              selector: ".product:nth-of-type(1) .product-info__body"
          - id: title_grade2
            label: Заголовок Grade 2
            type: string
            html:
              selector: ".product:nth-of-type(2) .header-product__title"
          - id: desc_grade2
            label: Описание Grade 2
            type: rich-text
            html:
              selector: ".product:nth-of-type(2) .product-info__body"

      - id: product_pellets
        label: Wood Pellets
        path: product_pellets.html
        fields:
          - id: title
            label: Название продукта
            type: string
            html:
              selector: ".header-product__title"
          - id: desc
            label: Описание продукта
            type: rich-text
            html:
              selector: ".product-info__body"

      - id: product_ruf
        label: RUF-briquettes
        path: product_ruf.html
        fields:
          - id: title
            label: Название продукта
            type: string
            html:
              selector: ".header-product__title"
          - id: desc
            label: Описание продукта
            type: rich-text
            html:
              selector: ".product-info__body"

      - id: product_timber
        label: Sawn Timber
        path: product_timber.html
        fields:
          - id: title
            label: Название продукта
            type: string
            html:
              selector: ".header-product__title"
          - id: desc
            label: Описание продукта
            type: rich-text
            html:
              selector: ".product-info__body"